services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./mysql_data:/var/lib/mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_lamp_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data: